### PR TITLE
added logo and background color

### PR DESCRIPTION
**Pull request by zainimran**
- Added logo
- Added some color to the footer and the page background to match the logo 
image

### CODE REVIEW

**Comment by achanana** [comment]
Looks good, did we want to go forward with "Locastic", or "Loctastic"?

**Comment by zainimran** [comment]
Locastic looks much cleaner and easier to speak/read. What do you think? Changing it wouldn't be difficult.

**Comment by achanana** [comment]
> Locastic looks much cleaner and easier to speak/read. What do you think? Changing it wouldn't be difficult.

I believe we are using Loctastic in a lot of places (Slack channel, GitHub repo), and the course staff will probably be using Loctastic to refer to us. I leave it up to you.

**Review by achanana — APPROVED** [review]
Good stuff ⛴

**Pull request merged**
